version: '3.8'

services:
  transcriber:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=conversations
      - DB_USER=postgres
      - DB_PASSWORD=5607

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: conversations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5607
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
